#APPLICATION DETAILS
application.title=@project.name@
application.version=@project.version@

# Specify the custom file path for the H2 database
spring.datasource.url=jdbc:h2:file:${user.home}/.onemock/onemock;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.platform=h2

# Show SQL statements in the log
# spring.jpa.show-sql=true

# Automatically create and update the database schema based on entities
spring.jpa.hibernate.ddl-auto=update

# H2 Console enabled for development and debugging (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#BANNER DETAILS
spring.output.ansi.enabled=always

#SERVER DETAILS
server.port=8080

#LOG DETAILS
logging.level.root=INFO
