export const GlobalConstants = {
    methods: [
        "GET",
        "POST",
        "PUT",
        "PATCH",
        "DELETE",
        "COPY",
        "HEAD",
        "OPTIONS",
        "LINK",
        "UNLINK",
        "PURGE",
        "LOCK",
        "UNLOCK",
        "PROPFIND",
        "VIEW",
    ],
    methods_color: {
        GET: "#3094fc",
        POST: "#22c77c",
        PUT: "#fca02f",
        PATCH: "#00b087",
        DELETE: "#f93e3d",
        COPY: "white",
        HEAD: "#a94bfa",
        OPTIONS: "#4978a3",
        LINK: "white",
        UNLINK: "white",
        PURGE: "white",
        LOCK: "white",
        UNLOCK: "white",
        PROPFIND: "white",
        VIEW: "white",
    },
    methods_secondary_color: {
        GET: "#e8f3ff",
        POST: "#e8fff5",
        PUT: "#fff3e6",
        PATCH: "#e3fff9",
        DELETE: "#ffeded",
        COPY: "white",
        HEAD: "#f3e6ff",
        OPTIONS: "#d1e8ff",
        LINK: "white",
        UNLINK: "white",
        PURGE: "white",
        LOCK: "white",
        UNLOCK: "white",
        PROPFIND: "white",
        VIEW: "white",
    },
};
